export const ModalType = Object.freeze({
  NONE: "NONE",
  REFERRAL_LINK_MODAL: "REFERRAL_LINK_MODAL",
  REFERRAL_QR_CODE_MODAL: "REFERRAL_QR_CODE_MODAL",
  REFERRAL_DISCOUNT_CODE_MODAL: "REFERRAL_DISCOUNT_CODE_MODAL",
});
